### PR TITLE
Wbeck

### PR DESCRIPTION
**Pull request by wbeck1990**
Added code with predictions function, and made the number of years generalizeable in the loops. Also fixed some of the subscripts on the predictions, so I think they make more sense now.

### CODE REVIEW

**Comment by wbeck1990** [comment]
> Added code with predictions function, and made the number of years generalizeable in the loops. Also fixed some of the subscripts on the predictions, so I think they make more sense now.

Tagging @jzwart here

**Comment by jzwart** [comment]
Awesome, looks great!

**Comment by jzwart** [comment]
@immccull95 could you add me as a `Collaborator` to this project so I can approve PR's, etc.. I think I'm just a `Contributor` right now. Instructions [here](https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository)

**Comment by jzwart** [comment]
Thanks @immccull95! I didn't realize you had sent me a collaborator invite a while ago...

**Pull request merged**
